# Generated by Django 6.0 on 2025-12-27 16:21

import django.db.models.deletion
import recordings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Без названия', max_length=200)),
                ('audio_file', models.FileField(upload_to=recordings.models.audio_upload_path)),
                ('whisper_model', models.CharField(choices=[('tiny', 'Tiny - Самая быстрая (~75 MB)'), ('base', 'Base - Баланс (~150 MB)'), ('small', 'Small - Хорошее качество (~500 MB)'), ('medium', 'Medium - Высокое качество (~1.5 GB)'), ('large', 'Large - Наилучшее качество (~3 GB)')], default='base', max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Загружено'), ('processing', 'Обработка'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='uploaded', max_length=20)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, help_text='Длительность в секундах', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_whisper_model', models.CharField(choices=[('tiny', 'Tiny - Самая быстрая (~75 MB)'), ('base', 'Base - Баланс (~150 MB)'), ('small', 'Small - Хорошее качество (~500 MB)'), ('medium', 'Medium - Высокое качество (~1.5 GB)'), ('large', 'Large - Наилучшее качество (~3 GB)')], default='base', max_length=10, verbose_name='Модель Whisper по умолчанию')),
                ('auto_transcribe', models.BooleanField(default=False, verbose_name='Автоматически распознавать после загрузки')),
                ('language', models.CharField(default='ru', max_length=10, verbose_name='Язык распознавания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
    ]
