# Generated by Django 5.2.9 on 2025-12-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='ID задачи Celery для отмены', max_length=255, null=True),
        ),
    ]
