# Generated by Django 5.2.9 on 2025-12-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_recording_recognition_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='recognition_service',
            field=models.CharField(choices=[('whisper', 'OpenAI Whisper (стандартный, высокое качество)'), ('faster-whisper', 'Faster-Whisper (4-5x быстрее, CTranslate2)'), ('vosk', 'Vosk (offline, очень быстрое распознавание)')], default='faster-whisper', max_length=20, verbose_name='Библиотека распознавания'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='whisper_model',
            field=models.CharField(blank=True, choices=[('tiny', 'Tiny - Самая быстрая (~75 MB, ~2-5x реального времени)'), ('base', 'Base - Баланс (~150 MB, ~1-3x реального времени)'), ('small', 'Small - Хорошее качество (~500 MB, ~0.5-1x реального времени)'), ('medium', 'Medium - Высокое качество (~1.5 GB, очень медленно, может занять 10-30+ минут)'), ('large', 'Large - Наилучшее качество (~3 GB, очень медленно, может занять 20-60+ минут)')], default='base', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='default_recognition_service',
            field=models.CharField(choices=[('whisper', 'OpenAI Whisper (стандартный, высокое качество)'), ('faster-whisper', 'Faster-Whisper (4-5x быстрее, CTranslate2)'), ('vosk', 'Vosk (offline, очень быстрое распознавание)')], default='faster-whisper', max_length=20, verbose_name='Библиотека распознавания по умолчанию'),
        ),
    ]
