# Generated by Django 5.2.9 on 2025-12-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_alter_recording_recognition_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='vosk_model',
            field=models.CharField(blank=True, help_text='Идентификатор модели Vosk (например, small-ru-0.22)', max_length=50, null=True, verbose_name='Модель Vosk'),
        ),
    ]
