# Generated by Django 5.2.9 on 2025-12-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0005_recording_vosk_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='default_vosk_model',
            field=models.CharField(blank=True, help_text='Идентификатор модели Vosk (например, small-ru-0.22)', max_length=50, null=True, verbose_name='Модель Vosk по умолчанию'),
        ),
    ]
